### ISSUE TITLE
Application into something like Python or JS?

### ISSUE THREAD

**Issue by DonaldTsang** [vseloved/wiki-lang-detect#4]
Is it possible to move the model into something more usable like Python or JS for webdev and such?

**Comment by vseloved** [comment]
Sure, go ahead

**Comment by DonaldTsang** [comment]
@vseloved how does it work exactly, purely by counting N-grmas or something much more complex?

**Comment by vseloved** [comment]
Here is the presentation with some details: https://www.slideshare.net/vseloved/nlp-in-the-wild-or-building-a-system-for-text-language-identification

Also, by the way, the system is dockerized so if you need just the results of processing, you can use this image: https://hub.docker.com/r/chaliy/wiki-lang-detect
